### ISSUE TITLE
Unload ahci and co

### ISSUE THREAD

**Issue by vogelfreiheit** [thopiekar/rcraid-dkms#3]
Seems impossible to unload ahci and libahci on runtime here. What is the impact of blacklisting them? Especially in the context of other SSDs/drives present.

Seems like without that, rcraid does not detect the RAID arrays. I'm on a x399 Threadripper system here.

**Comment by thopiekar** [comment]
I guess the reason why you can't unload them, is, because they are in use. Additionally, I can imagine that other hardware, like USB-to-SATA or similar devices, might need it to build up a connection.
Actually, I'm not using the RAID function on my board at the moment, because I don't trust AMD that much at the moment that the Windows driver will be maintained always good.
Since I have a dual boot setup and you can not put specific devices into a RAID, I better don't use it.
But I know that @Herrie82 is using it. Maybe he can give a hint, whether backlisting is needed and/or how he managed to get her/his setup running :wink:

**Comment by Herrie82** [comment]
Well I'm no Linux expert... My first time with Linux on desktop after having used it for a day on and off years ago and running it in VirtualBox for past years. I put to RAID mode in BIOS and only my non-RAID drives were seen in KUbuntu 18.04 without these RAID drivers. When I then installed them, all my arrays appeared in KUbuntu and seem to work fine.

**Comment by thopiekar** [comment]
@Herrie82 You mean all drives, which are not connected to the SATA controller?
In my case after formatting a drive, adding a drive to an array and trying to install Windows, I had to use the RAID drivers by AMD.
When trying to install Ubuntu, I was missing the rcraid driver and therefore no drive was seen.
So normally you should be not able to see any M2 or SATA drive without the needed driver.
However, the system became unattractive, because I wanted to clone only my data harddisk and not the SSD drive where I have Windows and Linux installed.
So you can either be in RAID or AHCI mode. A "mixed" mode is not possible.

**Comment by thopiekar** [comment]
Or wait, you mean you are running your computer on such a mixed mode?
Only needed to install the drivers?

That's sounds interesting. Thought all drives, which shall be detected by the OS must be in an array. If it shall work like a "regular" device, then it must be in a RAID 0. However, to add it there, it should be formatted.
That is what I believed so far. Am I wrong?

**Comment by Herrie82** [comment]
I have mixed mode. Some arrays and some single disks. No problem :) You just need the RAID drivers for the arrays to work.

**Comment by thopiekar** [comment]
Tried to get it working in the last days again, but without any success.
Only thing I noticed is that the rcraid driver is not included in initramfs, so if your system is on a RAID it won't boot, because the driver on the disk is not accessible.

**Comment by Herrie82** [comment]
My OS (boot) disk is not in RAID (M.2. SSD), I have other (data) disks that are in RAID. Just to clarify.

**Comment by thopiekar** [comment]
Oh, ok. That explains.
From what I see, it is possible to run the boot disk in legacy mode (not managed by RAID), but it is really difficult to replace the AHCI driver.
Additionally, I'm not a fan of blacklisting the ahci driver, because then you won't be able to come back from RAID to AHCI. That might be needed for example, when the rcraid driver gets broken.

**Comment by thopiekar** [comment]
Ok, managed to boot using a RAID disk.
All I had to do is adding "modprobe.blacklist=ahci" to the kernel's commandline.

**Comment by thopiekar** [comment]
Added some instructions via: 8029a13079f4ebc9070f77d4e62bc0b9b9819f38
